# Generated by Django 4.2.10 on 2024-02-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shortcuts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.CharField(blank=True, max_length=50)),
                ("title", models.CharField(blank=True, max_length=100)),
                ("summary", models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
